name = "youtube-playlist-converter-to-iwasync"
main = "src/index.js"
compatibility_date = "2025-04-22"

routes = [
  {pattern = "yt-to-is3.potapoyo.com", custom_domain = true}
]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

